name: Run Playwright and Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (Playwright)
        working-directory: ./fulltest
        run: npm install

      - name: Install Playwright Browsers
        working-directory: ./fulltest
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./fulltest
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: fulltest/playwright-report/
          retention-days: 30

      - name: Install dependencies (Cypress)
        working-directory: ./cypress_automation
        run: npm install

      - name: Run Cypress tests
        working-directory: ./cypress_automation
        run: npx cypress run

      - name: Generate Allure Report
        working-directory: ./cypress_automation
        run: |
          npm install -g allure-commandline
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: cypress_automation/allure-report
          retention-days: 30
