name: CI - Cypress & Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cypress_automation
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: npm run test
      - name: Upload Cypress results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results || cypress/screenshots || cypress/videos

  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fulltest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Verify browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm test
      - name: Upload Playwright results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: playwright-report || test-results || videos || screenshots
