name: E2E Tests (Playwright & Cypress)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  playwright-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci
        working-directory: fulltest

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: fulltest

      - name: Run Playwright Tests
        run: npx playwright test
        working-directory: fulltest

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: fulltest/playwright-report/
          retention-days: 14

  cypress-tests:
    name: Run Cypress Tests with Allure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: cypress_automation

      - name: Run Cypress Tests
        run: npx cypress run
        working-directory: cypress_automation

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          npx allure generate allure-results --clean -o allure-report
        working-directory: cypress_automation

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: cypress_automation/allure-report/
          retention-days: 14
